name: DevOps - Unit and Integration Tests
on:
  push:
    branches: [ 'main', 'develop', 'release-*' ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: '1' }
      - uses: actions/setup-java@v1
        with: { java-version: 17 }
      - name: Unit & Integration Tests
        run: mvn -B clean verify
      - name: Sonarcloud
        if: success() # Only perform code analysis if tests are passing
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=jdjuli_miw-iwvg-devops
          -Dsonar.organization=jdjuli
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}